window.KANJI_N5_DATA = [
  { kanji: '日', reading: 'にち', meaning: 'sun, day', example: '日本語' },
  { kanji: '月', reading: 'つき', meaning: 'moon, month', example: '月曜日' },
  { kanji: '金', reading: 'かね', meaning: 'gold, money', example: 'お金' },
  { kanji: '水', reading: 'みず', meaning: 'water', example: '水道' },
  { kanji: '火', reading: 'ひ', meaning: 'fire', example: '火曜日' },
  { kanji: '木', reading: 'き', meaning: 'tree, wood', example: '木の家' },
  { kanji: '土', reading: 'つち', meaning: 'earth, soil', example: '土の色' },
  { kanji: '車', reading: 'くるま', meaning: 'car, vehicle', example: '電車' },
  { kanji: '門', reading: 'もん', meaning: 'gate', example: '学校の門' },
  { kanji: '田', reading: 'た', meaning: 'rice field', example: '田んぼ' },
  { kanji: '山', reading: 'やま', meaning: 'mountain', example: '山道' },
  { kanji: '川', reading: 'かわ', meaning: 'river', example: '川の流れ' },
  { kanji: '雨', reading: 'あめ', meaning: 'rain', example: '雨が降る' },
  { kanji: '天', reading: 'あめ', meaning: 'heaven', example: '天気' },
  { kanji: '気', reading: 'き', meaning: 'spirit, air', example: '元気' },
  { kanji: '父', reading: 'ちち', meaning: 'father', example: '父の仕事' },
  { kanji: '母', reading: 'はは', meaning: 'mother', example: '母の手' },
  { kanji: '私', reading: 'わたし', meaning: 'I, private', example: '私は学生' },
  { kanji: '兄', reading: 'あに', meaning: 'older brother', example: '兄は先生' },
  { kanji: '姉', reading: 'あね', meaning: 'older sister', example: '姉がいる' },
  { kanji: '弟', reading: 'おとうと', meaning: 'younger brother', example: '弟が小さい' },
  { kanji: '妹', reading: 'いもうと', meaning: 'younger sister', example: '妹の名前' },
  { kanji: '一', reading: 'いち', meaning: 'one', example: '一日' },
  { kanji: '二', reading: 'に', meaning: 'two', example: '二人' },
  { kanji: '三', reading: 'さん', meaning: 'three', example: '三つ' },
  { kanji: '四', reading: 'よん', meaning: 'four', example: '四人' },
  { kanji: '五', reading: 'ご', meaning: 'five', example: '五分' },
  { kanji: '六', reading: 'ろく', meaning: 'six', example: '六時' },
  { kanji: '七', reading: 'なな', meaning: 'seven', example: '七日' },
  { kanji: '八', reading: 'はち', meaning: 'eight', example: '八時' },
  { kanji: '九', reading: 'きゅう', meaning: 'nine', example: '九月' },
  { kanji: '十', reading: 'じゅう', meaning: 'ten', example: '十人' },
  { kanji: '百', reading: 'ひゃく', meaning: 'hundred', example: '百円' },
  { kanji: '千', reading: 'せん', meaning: 'thousand', example: '千円' },
  { kanji: '万', reading: 'まん', meaning: 'ten thousand', example: '一万' },
  { kanji: '円', reading: 'えん', meaning: 'yen, circle', example: '百円' },
  { kanji: '年', reading: 'ねん', meaning: 'year', example: '今年' },
  { kanji: '半', reading: 'はん', meaning: 'half', example: '半分' },
  { kanji: '分', reading: 'ふん', meaning: 'minute, divide', example: '十分' },
  { kanji: '時', reading: 'じ', meaning: 'time, hour', example: '時間' },
  { kanji: '人', reading: 'ひと', meaning: 'person', example: '日本人' },
  { kanji: '女', reading: 'おんな', meaning: 'woman', example: '女の人' },
  { kanji: '生', reading: 'せい', meaning: 'life, born', example: '学生' },
  { kanji: '子', reading: 'こ', meaning: 'child', example: '子ども' },
  { kanji: '学', reading: 'がく', meaning: 'study, learning', example: '学校' },
  { kanji: '先', reading: 'さき', meaning: 'previous, ahead', example: '先生' },
  { kanji: '白', reading: 'しろ', meaning: 'white', example: '白い' },
  { kanji: '口', reading: 'くち', meaning: 'mouth', example: '口' },
  { kanji: '石', reading: 'いし', meaning: 'stone', example: '石ころ' },
  { kanji: '手', reading: 'て', meaning: 'hand', example: '手' },
  { kanji: '足', reading: 'あし', meaning: 'foot, leg', example: '足' },
  { kanji: '耳', reading: 'みみ', meaning: 'ear', example: '耳' },
  { kanji: '目', reading: 'め', meaning: 'eye', example: '目' },
  { kanji: '体', reading: 'からだ', meaning: 'body', example: '体' },
  { kanji: '上', reading: 'うえ', meaning: 'up, above', example: '上' },
  { kanji: '下', reading: 'した', meaning: 'down, below', example: '下' },
  { kanji: '中', reading: 'なか', meaning: 'middle, inside', example: '中' },
  { kanji: '大', reading: 'おお', meaning: 'big, large', example: '大きい' },
  { kanji: '小', reading: 'ちい', meaning: 'small', example: '小さい' },
  { kanji: '本', reading: 'もと', meaning: 'book, origin', example: '本' },
  { kanji: '力', reading: 'ちから', meaning: 'power, strength', example: '力' },
  { kanji: '何', reading: 'なに', meaning: 'what', example: '何ですか' },
  { kanji: '出', reading: 'でる', meaning: 'to exit', example: '出る' },
  { kanji: '入', reading: 'いる', meaning: 'to enter', example: '入る' },
  { kanji: '明', reading: 'あかり', meaning: 'bright, light', example: '明るい' },
  { kanji: '休', reading: 'やすむ', meaning: 'rest', example: '休む' },
  { kanji: '好', reading: 'このむ', meaning: 'like, be fond of', example: '好き' },
  { kanji: '男', reading: 'おとこ', meaning: 'man, male', example: '男の子' },
  { kanji: '間', reading: 'あいだ', meaning: 'interval, space', example: '時間' },
  { kanji: '岩', reading: 'いわ', meaning: 'rock', example: '岩' },
  { kanji: '畑', reading: 'はたけ', meaning: 'field', example: '畑' },
  { kanji: '森', reading: 'もり', meaning: 'forest', example: '森' },
  { kanji: '林', reading: 'はやし', meaning: 'woods', example: '林' },
  { kanji: '右', reading: 'みぎ', meaning: 'right', example: '右' },
  { kanji: '左', reading: 'ひだり', meaning: 'left', example: '左' },
  { kanji: '東', reading: 'ひがし', meaning: 'east', example: '東' },
  { kanji: '西', reading: 'にし', meaning: 'west', example: '西' },
  { kanji: '北', reading: 'きた', meaning: 'north', example: '北' },
  { kanji: '南', reading: 'みなみ', meaning: 'south', example: '南' },
  { kanji: '外', reading: 'そと', meaning: 'outside', example: '外' },
  { kanji: '駅', reading: 'えき', meaning: 'station', example: '駅' },
  { kanji: '会', reading: 'あう', meaning: 'meeting, association', example: '会う' },
  { kanji: '内', reading: 'うち', meaning: 'inside', example: '内側' },
  { kanji: '長', reading: 'ながい', meaning: 'long, leader', example: '長い' },
  { kanji: '高', reading: 'たかい', meaning: 'high, expensive', example: '高い' },
  { kanji: '名', reading: 'な', meaning: 'name', example: '名前' },
  { kanji: '行', reading: 'いく', meaning: 'to go', example: '行く' },
  { kanji: '来', reading: 'くる', meaning: 'to come', example: '来る' },
  { kanji: '食', reading: 'たべる', meaning: 'to eat', example: '食べる' },
  { kanji: '見', reading: 'みる', meaning: 'to see, look', example: '見る' },
  { kanji: '聞', reading: 'きく', meaning: 'to hear, listen', example: '聞く' },
  { kanji: '読', reading: 'よむ', meaning: 'to read', example: '読む' },
  { kanji: '書', reading: 'かく', meaning: 'to write', example: '書く' },
  { kanji: '話', reading: 'はなす', meaning: 'to speak, talk', example: '話す' },
  { kanji: '午', reading: 'ご', meaning: 'noon', example: '午前' },
  { kanji: '前', reading: 'まえ', meaning: 'before, in front', example: '前' },
  { kanji: '後', reading: 'あと', meaning: 'after, behind', example: '後ろ' },
  { kanji: '毎', reading: 'まい', meaning: 'every', example: '毎日' },
  { kanji: '校', reading: 'こう', meaning: 'school', example: '学校' },
  { kanji: '語', reading: 'ご', meaning: 'language, word', example: '日本語' },
  { kanji: '今', reading: 'いま', meaning: 'now', example: '今' },
  { kanji: '電', reading: 'でん', meaning: 'electricity', example: '電車' },
  { kanji: '国', reading: 'くに', meaning: 'country', example: '国' }
];
