window.KANJI_N4_DATA = [
  { kanji: '魚', reading: 'さかな', meaning: 'fish', example: '魚を食べる' },
  { kanji: '鳥', reading: 'とり', meaning: 'bird', example: '鳥がいる' },
  { kanji: '馬', reading: 'うま', meaning: 'horse', example: '馬を見た' },
  { kanji: '牛', reading: 'うし', meaning: 'cow', example: '牛乳' },
  { kanji: '物', reading: 'もの', meaning: 'thing, object', example: '物を買う' },
  { kanji: '肉', reading: 'にく', meaning: 'meat', example: '肉料理' },
  { kanji: '貝', reading: 'かい', meaning: 'shellfish', example: '貝がら' },
  { kanji: '竹', reading: 'たけ', meaning: 'bamboo', example: '竹の矢' },
  { kanji: '米', reading: 'こめ', meaning: 'rice', example: '米屋' },
  { kanji: '糸', reading: 'いと', meaning: 'thread', example: '糸で縫う' },
  { kanji: '花', reading: 'はな', meaning: 'flower', example: '花が咲く' },
  { kanji: '茶', reading: 'ちゃ', meaning: 'tea', example: 'お茶' },
  { kanji: '字', reading: 'じ', meaning: 'character', example: '字の練習' },
  { kanji: '文', reading: 'ぶん', meaning: 'sentence, writing', example: '文を書く' },
  { kanji: '新', reading: 'あたらしい', meaning: 'new', example: '新しい店' },
  { kanji: '古', reading: 'ふるい', meaning: 'old', example: '古い本' },
  { kanji: '短', reading: 'みじかい', meaning: 'short', example: '短い時間' },
  { kanji: '安', reading: 'やすい', meaning: 'cheap, safe', example: '安い店' },
  { kanji: '低', reading: 'ひくい', meaning: 'low', example: '低い山' },
  { kanji: '暗', reading: 'くらい', meaning: 'dark', example: '暗い部屋' },
  { kanji: '多', reading: 'おおい', meaning: 'many', example: '多くの人' },
  { kanji: '少', reading: 'すくない', meaning: 'few, little', example: '少し' },
  { kanji: '帰', reading: 'かえる', meaning: 'return', example: '家に帰る' },
  { kanji: '飲', reading: 'のむ', meaning: 'drink', example: '水を飲む' },
  { kanji: '教', reading: 'おしえる', meaning: 'teach', example: '先生が教える' },
  { kanji: '買', reading: 'かう', meaning: 'buy', example: '本を買う' },
  { kanji: '売', reading: 'うる', meaning: 'sell', example: '店で売る' },
  { kanji: '開', reading: 'あく', meaning: 'open', example: 'ドアが開く' },
  { kanji: '閉', reading: 'しめる', meaning: 'close', example: '窓を閉める' },
  { kanji: '飯', reading: 'めし', meaning: 'meal, rice', example: '朝ご飯' },
  { kanji: '歌', reading: 'うた', meaning: 'song', example: '歌を歌う' },
  { kanji: '曜', reading: 'よう', meaning: 'day of week', example: '月曜日' },
  { kanji: '週', reading: 'しゅう', meaning: 'week', example: '一週間' },
  { kanji: '方', reading: 'ほう', meaning: 'direction, way', example: 'この方' },
  { kanji: '夕', reading: 'ゆう', meaning: 'evening', example: '夕方' },
  { kanji: '朝', reading: 'あさ', meaning: 'morning', example: '朝ごはん' },
  { kanji: '昼', reading: 'ひる', meaning: 'daytime', example: '昼ご飯' },
  { kanji: '夜', reading: 'よる', meaning: 'night', example: '夜歩く' },
  { kanji: '晩', reading: 'ばん', meaning: 'evening', example: '晩ご飯' },
  { kanji: '友', reading: 'とも', meaning: 'friend', example: '友だち' },
  { kanji: '夫', reading: 'おっと', meaning: 'husband', example: '夫の仕事' },
  { kanji: '妻', reading: 'つま', meaning: 'wife', example: '妻と話す' },
  { kanji: '彼', reading: 'かれ', meaning: 'he, boyfriend', example: '彼が来る' },
  { kanji: '主', reading: 'おも', meaning: 'main, master', example: '主な問題' },
  { kanji: '奥', reading: 'おく', meaning: 'interior, back', example: '奥さん' },
  { kanji: '海', reading: 'うみ', meaning: 'sea', example: '海で泳ぐ' },
  { kanji: '泳', reading: 'およぐ', meaning: 'swim', example: 'プールで泳ぐ' },
  { kanji: '油', reading: 'あぶら', meaning: 'oil', example: '油を使う' },
  { kanji: '待', reading: 'まつ', meaning: 'wait', example: '駅で待つ' },
  { kanji: '計', reading: 'はかる', meaning: 'measure, plan', example: '計画' },
  { kanji: '酒', reading: 'さけ', meaning: 'alcohol', example: '酒を飲む' },
  { kanji: '作', reading: 'つくる', meaning: 'make', example: '料理を作る' },
  { kanji: '部', reading: 'ぶ', meaning: 'section', example: '部屋' },
  { kanji: '院', reading: 'いん', meaning: 'institution', example: '病院' },
  { kanji: '宅', reading: 'たく', meaning: 'house', example: '自宅' },
  { kanji: '客', reading: 'きゃく', meaning: 'guest', example: 'お客さん' },
  { kanji: '室', reading: 'しつ', meaning: 'room', example: '教室' },
  { kanji: '家', reading: 'いえ', meaning: 'house', example: '家に帰る' },
  { kanji: '英', reading: 'えい', meaning: 'English', example: '英語' },
  { kanji: '薬', reading: 'くすり', meaning: 'medicine', example: '薬を飲む' },
  { kanji: '雲', reading: 'くも', meaning: 'cloud', example: '雲が多い' },
  { kanji: '雪', reading: 'ゆき', meaning: 'snow', example: '雪が降る' },
  { kanji: '言', reading: 'いう', meaning: 'say', example: '言う' },
  { kanji: '広', reading: 'ひろい', meaning: 'wide', example: '広い部屋' },
  { kanji: '店', reading: 'みせ', meaning: 'shop', example: '店に行く' },
  { kanji: '度', reading: 'ど', meaning: 'degree, time', example: '三度' },
  { kanji: '病', reading: 'やまい', meaning: 'illness', example: '病気' },
  { kanji: '疲', reading: 'つかれる', meaning: 'tired', example: '疲れる' },
  { kanji: '屋', reading: 'や', meaning: 'shop', example: '八百屋' },
  { kanji: '回', reading: 'かい', meaning: 'time, round', example: '一回' },
  { kanji: '困', reading: 'こまる', meaning: 'be troubled', example: '困る' },
  { kanji: '近', reading: 'ちかい', meaning: 'near', example: '近い駅' },
  { kanji: '遠', reading: 'とおい', meaning: 'far', example: '遠い場所' },
  { kanji: '速', reading: 'はやい', meaning: 'fast', example: '速い車' },
  { kanji: '遅', reading: 'おそい', meaning: 'slow', example: '遅い電車' },
  { kanji: '道', reading: 'みち', meaning: 'road, way', example: '道を歩く' },
  { kanji: '青', reading: 'あお', meaning: 'blue, green', example: '青い空' },
  { kanji: '晴', reading: 'はれる', meaning: 'clear up', example: '晴れる' },
  { kanji: '静', reading: 'しずか', meaning: 'quiet', example: '静かな町' },
  { kanji: '寺', reading: 'てら', meaning: 'temple', example: '寺を見た' },
  { kanji: '持', reading: 'もつ', meaning: 'hold', example: 'かばんを持つ' },
  { kanji: '荷', reading: 'に', meaning: 'baggage', example: '荷物' },
  { kanji: '元', reading: 'もと', meaning: 'origin', example: '元気' },
  { kanji: '有', reading: 'ある', meaning: 'have', example: '有名' },
  { kanji: '親', reading: 'おや', meaning: 'parents', example: '親と話す' },
  { kanji: '切', reading: 'きる', meaning: 'cut', example: '切る' },
  { kanji: '便', reading: 'びん', meaning: 'convenience', example: '便り' },
  { kanji: '利', reading: 'り', meaning: 'benefit', example: '便利' },
  { kanji: '不', reading: 'ふ', meaning: 'not', example: '不安' },
  { kanji: '若', reading: 'わかい', meaning: 'young', example: '若い人' },
  { kanji: '早', reading: 'はやい', meaning: 'early', example: '早い' },
  { kanji: '忙', reading: 'いそがしい', meaning: 'busy', example: '忙しい' },
  { kanji: '乗', reading: 'のる', meaning: 'ride', example: '電車に乗る' },
  { kanji: '降', reading: 'おりる', meaning: 'go down', example: '駅で降りる' },
  { kanji: '着', reading: 'きる', meaning: 'wear, arrive', example: '着く' },
  { kanji: '渡', reading: 'わたる', meaning: 'cross, hand over', example: '橋を渡る' },
  { kanji: '通', reading: 'とおる', meaning: 'pass through', example: '道を通る' },
  { kanji: '走', reading: 'はしる', meaning: 'run', example: '走る' },
  { kanji: '歩', reading: 'あるく', meaning: 'walk', example: '歩く' },
  { kanji: '止', reading: 'とまる', meaning: 'stop', example: '止まる' },
  { kanji: '動', reading: 'うごく', meaning: 'move', example: '動く' },
  { kanji: '働', reading: 'はたらく', meaning: 'work', example: '働く' },
  { kanji: '鉄', reading: 'てつ', meaning: 'iron', example: '鉄道' },
  { kanji: '工', reading: 'こう', meaning: 'craft, industry', example: '工場' },
  { kanji: '場', reading: 'ば', meaning: 'place', example: '場所' },
  { kanji: '地', reading: 'ち', meaning: 'ground', example: '地図' },
  { kanji: '館', reading: 'かん', meaning: 'hall', example: '美術館' },
  { kanji: '公', reading: 'こう', meaning: 'public', example: '公園' },
  { kanji: '園', reading: 'えん', meaning: 'garden', example: '公園' },
  { kanji: '住', reading: 'すむ', meaning: 'live', example: '住む' },
  { kanji: '所', reading: 'ところ', meaning: 'place', example: '場所' },
  { kanji: '番', reading: 'ばん', meaning: 'number', example: '番号' },
  { kanji: '号', reading: 'ごう', meaning: 'number', example: '号室' },
  { kanji: '市', reading: 'し', meaning: 'city', example: '市役所' },
  { kanji: '町', reading: 'まち', meaning: 'town', example: '町へ行く' },
  { kanji: '村', reading: 'むら', meaning: 'village', example: '村' },
  { kanji: '区', reading: 'く', meaning: 'ward', example: '区役所' },
  { kanji: '都', reading: 'と', meaning: 'metropolis', example: '東京都' },
  { kanji: '府', reading: 'ふ', meaning: 'prefecture', example: '大阪府' },
  { kanji: '県', reading: 'けん', meaning: 'prefecture', example: '県立' },
  { kanji: '島', reading: 'しま', meaning: 'island', example: '島に行く' },
  { kanji: '京', reading: 'きょう', meaning: 'capital', example: '東京' },
  { kanji: '様', reading: 'さま', meaning: 'appearance, sir', example: 'お客様' },
  { kanji: '練', reading: 'ねる', meaning: 'practice', example: '練習' },
  { kanji: '習', reading: 'ならう', meaning: 'learn', example: '勉強する' },
  { kanji: '勉', reading: 'べん', meaning: 'diligence', example: '勉強' },
  { kanji: '強', reading: 'つよい', meaning: 'strong', example: '強い' },
  { kanji: '研', reading: 'けん', meaning: 'study, polish', example: '研究' },
  { kanji: '究', reading: 'きゅう', meaning: 'research', example: '研究' },
  { kanji: '留', reading: 'とめる', meaning: 'stay', example: '留学' },
  { kanji: '質', reading: 'しつ', meaning: 'quality', example: '質問' },
  { kanji: '問', reading: 'とく', meaning: 'question', example: '問題' },
  { kanji: '題', reading: 'だい', meaning: 'topic', example: '問題' },
  { kanji: '答', reading: 'こたえる', meaning: 'answer', example: '答える' },
  { kanji: '宿', reading: 'やど', meaning: 'inn, lodging', example: '宿題' },
  { kanji: '政', reading: 'せい', meaning: 'government', example: '政治' },
  { kanji: '治', reading: 'おさめる', meaning: 'govern', example: '政治' },
  { kanji: '経', reading: 'けい', meaning: 'pass through', example: '経済' },
  { kanji: '済', reading: 'すむ', meaning: 'finish', example: '経済' },
  { kanji: '史', reading: 'し', meaning: 'history', example: '歴史' },
  { kanji: '育', reading: 'そだつ', meaning: 'nurture', example: '教育' },
  { kanji: '化', reading: 'か', meaning: 'change, culture', example: '文化' },
  { kanji: '理', reading: 'り', meaning: 'principle', example: '理科' },
  { kanji: '科', reading: 'か', meaning: 'department', example: '理科' },
  { kanji: '数', reading: 'かず', meaning: 'number', example: '数学' },
  { kanji: '医', reading: 'い', meaning: 'medicine', example: '医者' }
];
